<?php

namespace common\models;

use app\modules\GMS\controllers\GmsSendersController;
use Yii;

/**
 * This is the model class for table "gms_playlist".
 *
 * @property integer $id
 * @property string $name
 * @property string $file
 * @property integer $type
 * @property integer $region
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $sender_id
 * @property string $jsonPlaylist
 * @property GmsRegions $regionModel
 * @property GmsSenders $senderModel
 */

class GmsPlaylist extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gms_playlist';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['region', 'type'], 'required'],
            [['type', 'region', 'created_at', 'updated_at', 'sender_id'], 'integer'],
            [['name', 'file'], 'string', 'max' => 255],
            [['jsonPlaylist'], 'string'],
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
            $this->created_at = time();
        else
            $this->updated_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'file' => 'Имя файла',
            'type' => 'Тип шаблона',
            'region' => 'Регион прогрывания',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата редактирования',
            'jsonPlaylist' => 'Плейлист',
            'sender_id' => 'Код отделения',
            'sender_name' => 'Отделение'
        ];
    }

    /**
     * @param null $id
     * @return array|mixed
     */
    public static function getPlayListType($id = null) {
        $arr =  ['1' => 'Стандартный', '2' => 'Коммерческий'];
        return is_null($id) ? $arr : $arr[$id];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegionModel()
    {
        return $this->hasOne(GmsRegions::className(), ['id' => 'region']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSenderModel()
    {
        return $this->hasOne(GmsSenders::className(), ['id' => 'sender_id']);
    }
}
