<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "rep_PeriodLabGemotest".
 *
 * @property int $id
 * @property string $date_start
 * @property string $date_end
 * @property string $sender_id
 * @property string $login
 * @property string $pass
 * @property string $date_active
 * @property double $reward
 * @property int $test_period
 * @property string $deleted
 * @property string $contract
 * @property int $user_id
 */
class RepPeriodLabGemotest extends \yii\db\ActiveRecord
{
    public $contract;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'rep_PeriodLabGemotest';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('GemoTestDB');
    }

    public function afterFind()
    {
        $this->contract = 'ЛД'.$this->id;
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date_start'], 'required'],
            [['date_start', 'date_end', 'date_active', 'deleted'], 'safe'],
            [['sender_id', 'login', 'pass'], 'string'],
            [['reward'], 'number'],
            [['test_period', 'user_id'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date_start' => 'Дата начало',
            'date_end' => 'Дата конец',
            'sender_id' => 'Отделение',
            'login' => 'Логин',
            'pass' => 'Пароль',
            'date_active' => 'Дата активации',
            'reward' => 'Награда',
            'test_period' => 'Тестовый период',
            'deleted' => 'Удален',
            'user_id' => 'Пользователь',
            'contract' => 'Договор'
        ];
    }
}
