<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '1C Code' => 'Код контрагента в 1С',
    'Article View' => 'Шаблон статьи',
    'Page View' => 'Шаблон страницы',
    '"{attribute}" must be a valid JSON' => '"{attribute}" должен содержать валидный JSON',
    'Active' => 'Активно',
    'Additional Contacts' => 'Дополнительные контакты',
    'Article ID' => 'ID Статьи',
    'Author' => 'Автор',
    'Base URL' => 'Базовый URL',
    'Base Url' => 'Базовый Url',
    'Body' => 'Текст',
    'Caption' => 'Текст',
    'Carousel ID' => 'ID карусели',
    'Category' => 'Категория',
    'Cause' => 'Основание',
    'Comment' => 'Комментарий',
    'Company ID' => 'ID компании',
    'Component' => 'Компонент',
    'Config' => 'Настройки',
    'Created At' => 'Создано',
    'Created at' => 'Создано',
    'SM Access' => 'Доступ в МП',
    'Date' => 'Дата',
    'Deal' => 'Сделка',
    'Deleted' => 'Удалено',
    'Discount' => 'Скидка',
    'Down to maintenance.' => 'Закрыто на обслуживание',
    'E-mail' => 'E-mail',
    'File Type' => 'Тип файла',
    'Firstname' => 'Имя',
    'Flat' => 'Квартира',
    'Gender' => 'Пол',
    'House' => 'Дом',
    'Home' => 'Домашний',
    'ID' => 'ID',
    'Image' => 'Изображение',
    'Key' => 'Ключ',
    'Last login' => 'Последний вход',
    'Lastname' => 'Фамилия',
    'Legal' => 'Юр. статус',
    'Locale' => 'Локаль',
    'Location' => 'Местоположение',
    'Main' => 'Основной',
    'Middlename' => 'Отчество',
    'Client' => 'Клиент',
    'Contracts' => 'Договоры',
    'Cost Rest' => 'Остаток суммы',
    'Name' => 'Имя',
    'No' => 'Нет',
    'Order' => 'Порядок',
    'Objects' => 'Объекты',
    'Parent Category' => 'Родительская категория',
    'Payments Count' => 'Количество платежей',
    'Path' => 'Путь',
    'Passport' => 'Документ/ОС',
    'Performance' => 'Исполнение',
    'Picture' => 'Аватар',
    'Published' => 'Опубликовано',
    'Phone' => 'Телефон',
    'Phones' => 'Телефоны',
    'Published At' => 'Дата публикации',
    'Section' => 'Секция',
    'Size' => 'Размер',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'Stage' => 'Очередь',
    'Street' => 'Улица',
    'Sum' => 'Сумма',
    'Deal Sum' => "Сумма по сделке",
    'Thumbnail' => 'Эскиз изображения',
    'Title' => 'Название',
    'Type' => 'Тип',
    'Updated At' => 'Обновлено',
    'Updated at' => 'Последнее обновление',
    'Updater' => 'Обновивщий',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'ID пользователя',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',
    'Verified' => 'Верифицирован',
    'Working' => 'Рабочий',
    'Yes' => 'Да'
];
